
server:
  port: 8080


spring:
  mail:
    host: smtp.qq.com
    username: 1521955177@qq.com
    password: ekopgklrddvcbaac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hab?serverTimezone=GMT%2b8
  redis:
    password: root
    port: 6379
    host: localhost


mybatis:
    mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
